# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logit_pi <- function(pi, nclass) {
    .Call('_catlvm_logit_pi', PACKAGE = 'catlvm', pi, nclass)
}

logit_tau <- function(tau, nk, nl) {
    .Call('_catlvm_logit_tau', PACKAGE = 'catlvm', tau, nk, nl)
}

logit_rho <- function(rho, ncat, nclass) {
    .Call('_catlvm_logit_rho', PACKAGE = 'catlvm', rho, ncat, nclass)
}

pi_gnr <- function(nk) {
    .Call('_catlvm_pi_gnr', PACKAGE = 'catlvm', nk)
}

tau_gnr <- function(nk, nl) {
    .Call('_catlvm_tau_gnr', PACKAGE = 'catlvm', nk, nl)
}

rho_gnr <- function(nk, ncat) {
    .Call('_catlvm_rho_gnr', PACKAGE = 'catlvm', nk, ncat)
}

root_gnr <- function(nobs, nk, prob = NULL) {
    .Call('_catlvm_root_gnr', PACKAGE = 'catlvm', nobs, nk, prob)
}

cls_gnr <- function(nobs, nk, nl, v, prob = NULL) {
    .Call('_catlvm_cls_gnr', PACKAGE = 'catlvm', nobs, nk, nl, v, prob)
}

y_gnr <- function(nobs, nk, ncat, cls, prob = NULL) {
    .Call('_catlvm_y_gnr', PACKAGE = 'catlvm', nobs, nk, ncat, cls, prob)
}

ysim <- function(nsim, nlv, root, leaf, ulv, vlv, nclass, nroot, nleaf, nedge, ncat, cstr_leaf, pi, tau, rho, print_class) {
    .Call('_catlvm_ysim', PACKAGE = 'catlvm', nsim, nlv, root, leaf, ulv, vlv, nclass, nroot, nleaf, nedge, ncat, cstr_leaf, pi, tau, rho, print_class)
}

calcfreq <- function(mis, nrep, nmis, freq, xobs, nc, N, tol, max_iter) {
    .Call('_catlvm_calcfreq', PACKAGE = 'catlvm', mis, nrep, nmis, freq, xobs, nc, N, tol, max_iter)
}

par_gnr <- function(nobs, nvar, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, init, init_param) {
    .Call('_catlvm_par_gnr', PACKAGE = 'catlvm', nobs, nvar, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, init, init_param)
}

emFit <- function(y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf, init, init_param, max_iter, tol, verbose, periter = 100L) {
    .Call('_catlvm_emFit', PACKAGE = 'catlvm', y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf, init, init_param, max_iter, tol, verbose, periter)
}

floglik <- function(param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf) {
    .Call('_catlvm_floglik', PACKAGE = 'catlvm', param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf)
}

calclli <- function(param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf) {
    .Call('_catlvm_calclli', PACKAGE = 'catlvm', param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf)
}

calcPost <- function(param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf) {
    .Call('_catlvm_calcPost', PACKAGE = 'catlvm', param, y, nobs, nvar, ncat, nlv, nroot, nedge, nleaf, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_leaf, nclass, nclass_leaf)
}

logit2log <- function(param, nobs, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf) {
    .Call('_catlvm_logit2log', PACKAGE = 'catlvm', param, nobs, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf)
}

splitSE <- function(se, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf) {
    .Call('_catlvm_splitSE', PACKAGE = 'catlvm', se, ncat, nroot, nedge, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf)
}

