# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcll <- function(param, y, nobs, nvar, ncat, nlv, nroot, nlink, nlink_unique, nleaf, nleaf_unique, root, ulv, vlv, cstr_link, leaf, cstr_leaf, nclass, nclass_u, nclass_v, nclass_leaf) {
    .Call(`_catlvm_calcll`, param, y, nobs, nvar, ncat, nlv, nroot, nlink, nlink_unique, nleaf, nleaf_unique, root, ulv, vlv, cstr_link, leaf, cstr_leaf, nclass, nclass_u, nclass_v, nclass_leaf)
}

calcModel <- function(param, y, nobs, nvar, ncat, nlv, nroot, nlink, nleaf, nlink_unique, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_link, cstr_leaf, nclass, nclass_leaf, nclass_u, nclass_v) {
    .Call(`_catlvm_calcModel`, param, y, nobs, nvar, ncat, nlv, nroot, nlink, nleaf, nlink_unique, nleaf_unique, root, tree_index, ulv, vlv, leaf, cstr_link, cstr_leaf, nclass, nclass_leaf, nclass_u, nclass_v)
}

emFit <- function(y, nobs, nvar, ncat, nlv, nroot, nlink, nleaf, nlink_unique, nleaf_unique, tree_index, root, ulv, vlv, leaf, cstr_link, cstr_leaf, nclass, nclass_leaf, nclass_u, nclass_v, init, init_param, max_iter, tol, verbose, periter = 100L) {
    .Call(`_catlvm_emFit`, y, nobs, nvar, ncat, nlv, nroot, nlink, nleaf, nlink_unique, nleaf_unique, tree_index, root, ulv, vlv, leaf, cstr_link, cstr_leaf, nclass, nclass_leaf, nclass_u, nclass_v, init, init_param, max_iter, tol, verbose, periter)
}

floglik <- function(param, y, nobs, nvar, ncat, nlv, nroot, nlink, nlink_unique, nleaf, nleaf_unique, root, ulv, vlv, cstr_link, leaf, cstr_leaf, nclass, nclass_u, nclass_v, nclass_leaf) {
    .Call(`_catlvm_floglik`, param, y, nobs, nvar, ncat, nlv, nroot, nlink, nlink_unique, nleaf, nleaf_unique, root, ulv, vlv, cstr_link, leaf, cstr_leaf, nclass, nclass_u, nclass_v, nclass_leaf)
}

pi_gnr <- function(nk) {
    .Call(`_catlvm_pi_gnr`, nk)
}

tau_gnr <- function(nk, nl) {
    .Call(`_catlvm_tau_gnr`, nk, nl)
}

rho_gnr <- function(nk, ncat) {
    .Call(`_catlvm_rho_gnr`, nk, ncat)
}

par_gnr <- function(nobs, nvar, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, nclass_u, nclass_v, init, init_param) {
    .Call(`_catlvm_par_gnr`, nobs, nvar, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, nclass_u, nclass_v, init, init_param)
}

calcfreq <- function(mis, nrep, nmis, freq, xobs, nc, N, tol, max_iter) {
    .Call(`_catlvm_calcfreq`, mis, nrep, nmis, freq, xobs, nc, N, tol, max_iter)
}

root_gnr <- function(nobs, nk, prob = NULL) {
    .Call(`_catlvm_root_gnr`, nobs, nk, prob)
}

cls_gnr <- function(nobs, nk, nl, v, prob = NULL) {
    .Call(`_catlvm_cls_gnr`, nobs, nk, nl, v, prob)
}

y_gnr <- function(nobs, nk, ncat, cls, prob = NULL) {
    .Call(`_catlvm_y_gnr`, nobs, nk, ncat, cls, prob)
}

ysim <- function(nsim, nlv, root, leaf, ulv, vlv, cstr_link, cstr_leaf, nclass, nroot, nleaf, nlink, ncat, pi, tau, rho, print_class) {
    .Call(`_catlvm_ysim`, nsim, nlv, root, leaf, ulv, vlv, cstr_link, cstr_leaf, nclass, nroot, nleaf, nlink, ncat, pi, tau, rho, print_class)
}

logit_pi <- function(pi, nclass) {
    .Call(`_catlvm_logit_pi`, pi, nclass)
}

logit_tau <- function(tau, nk, nl) {
    .Call(`_catlvm_logit_tau`, tau, nk, nl)
}

logit_rho <- function(rho, ncat, nclass) {
    .Call(`_catlvm_logit_rho`, rho, ncat, nclass)
}

logit2log <- function(param, nobs, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, nclass_u, nclass_v) {
    .Call(`_catlvm_logit2log`, param, nobs, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_leaf, nclass_u, nclass_v)
}

splitSE <- function(se, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_u, nclass_v, nclass_leaf) {
    .Call(`_catlvm_splitSE`, se, ncat, nroot, nlink_unique, nleaf_unique, root, ulv, vlv, nclass, nclass_u, nclass_v, nclass_leaf)
}

